Automatically Update Data Options
toolsforexperiments/labcore pull request #51
Opened 2024-11-01 19:16 UTC by Rockyd3

Updated the plottr app to allow for continuous checking of everything within the directory the program is run from. If a new data directory is added, this automatically refreshes the options to show the new options.

Changed multi select widget to check box widget to better allow this. Made data options include dates to avoid duplicate file names getting lost.

2024-11-01 21:41 UTC, marcosfrenkel requested changes
Basic styling comments

2024-11-01 21:41 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
> +        #     pn.state.add_periodic_callback(self.load_and_preprocess, self.refresh.value * 1000)
Remove commented code

2024-11-01 21:41 UTC, marcosfrenkel commented on labcore/analysis/hvplotting.py
> +        except:
Add exception that you are trying to catch

2024-11-01 21:43 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
> +from watchdog.observers import Observer
Add watchdog as a requirement to the package

2024-11-01 21:44 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
> +class Handler(FileSystemEventHandler):
2 empty spaces between members (imports, functions, classes, etc)

2024-11-01 21:44 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
> +            self.update_callback(event)
Same, 2 spaces between this line and line underneath

2024-11-01 21:45 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
> +        self.image_feed_width = 400  # The width of images in the feed
Single blank line between code inside a function

2024-11-01 21:51 UTC, marcosfrenkel requested changes

2024-11-01 21:51 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
> +            # height=self.size,
Remove commented code

2024-11-01 21:51 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
>              stylesheets = [selector_stylesheet]
This is not on you, but can you remove the spaces between the `=`?

2024-11-01 21:51 UTC, marcosfrenkel commented on labcore/analysis/hvapps.py
> +
Too many empty lines between members of a class

2024-11-01 21:52 UTC, marcosfrenkel commented
So the way the this is working at the moment is that at any change you reload the entire data? You are not filtering what the event is and modifying only the necessary thing right?

2024-11-08 16:17 UTC, Rockyd3 commented
> So the way the this is working at the moment is that at any change you reload the entire data? You are not filtering what the event is and modifying only the necessary thing right?

That is correct. There is probably a better way to do this - I'm not sure what parts of the way data is stored are consistent/need to be consistent. I will look into making this occur with the current assumed data structure/labelling

2024-11-08 16:38 UTC, marcosfrenkel commented
We should have a little bit of a discussion in person about how to handle this. It might not be worth doing this now though, but focusing on other features before. Let's talk in person about this

2024-11-15 19:47 UTC, marcosfrenkel approved these changes
Looks good

2024-11-15 19:47 UTC, merged